### ISSUE TITLE
cannot add effects; modep crashes (jessie)

### ISSUE THREAD

**Issue by produnis** [BlokasLabs/modep#1]
Hi there, 
I did a manual install of modep on a fresh raspian-3B-pisound install (jessie).
I can browse to http:/my-pisound/  and I see the modep-webpage.

However, I cannot add any effects. If i drag an effect to the panel, I get the error message "cannot add effect". After some time, I get the message "Connection lost", and reloading the webpage gives me "webpage not available".

I need to reboot my pi in order to get back to the modep-webpage. However, I cannot add any effects.

Are there some logfiles I could go through?
Greetings
Joe

**Comment by lucianthorr** [comment]
I'm in the same boat.  New to Raspberry Pi's also so I could be missing something simple.
i installed modep and can log into the app via Chromium locally or Chrome via wifi but when I drag an effect into the pedalboard, I get a little spinner for a few seconds and then "Error adding effect."

**Comment by Pranciskus** [comment]
Can you post the output of running "modep" & selecting Tools > System Status?

**Comment by lucianthorr** [comment]
Looks like mod-monitor.servise has failed.
If I try to enable it through Tools>Enable MODEP systemd Services, it goes to "deactivated" and then "failed"
If I disable all services and then enable all services, they all go to active but then mod-monitor.servise seems to loop between 'deactivating' and 'active'

**Comment by Pranciskus** [comment]
And "sudo journalctl -u mod-monitor"?

**Comment by lucianthorr** [comment]
[output.txt](https://github.com/BlokasLabs/modep/files/1237200/output.txt)

**Comment by produnis** [comment]
mine gives:

Aug 20 18:36:01 pisound jack_load[1650]: Cannot read socket fd = 5 err = Success
Aug 20 18:36:01 pisound jack_load[1650]: CheckRes error
Aug 20 18:36:01 pisound jack_load[1650]: JackSocketClientChannel read fail
Aug 20 18:36:01 pisound systemd[1]: mod-monitor.service: main process exited, code=exited, status=1/FAILURE
Aug 20 18:36:01 pisound jack_load[1650]: Cannot open jack_load client
Aug 20 18:36:01 pisound jack_load[1650]: jack_client_open() failed, status = 0x21

**Comment by produnis** [comment]
here is a complete syslog:

https://pastebin.com/Esyz2cWu

**Comment by dcoredump** [comment]
Hi @ll,

I think the mod-monitor-plugin isn't really needed if you don't have a MOD-Duo. You can make a workaround with removing the start of mod-monitor and adding an alias to the PiSound input device and name it "mod-monitor". You can try my systemd-service-scripts for starting mod-host and mod-ui (https://github.com/dcoredump/zynthian-recipe inside mod_pisound).

Regards, Holger

**Comment by gtrainavicius** [comment]
The latest image shouldn't have this issue anymore: https://community.blokas.io/t/release-modep-2018-04-03/496
